seed_everything: 333

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 4000
  precision: 32-true
  log_every_n_steps: 50
  default_root_dir: saved_models/renaissance-none-resnet-bilstm-ctc
  # Uncomment the following lines to enable Weights & Biases logging. Make sure to set up your W&B account and API key.
  # logger:
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   init_args:
  #     project: project
  #     entity: entity
  #     name: name
  #     log_model: false

model:
  output_channel: 512
  hidden_size: 256
  lr: 0.0001
  pretrained_path: ""
  wandb_log_every_n_epochs: 100
  wandb_num_logs: 8

data:
  dataset_csv: data/filtered_spanish_dataset_no_accents.csv
  image_root: data
  val_indices: [1]
  test_indices: []
  workers: 0
  batch_size: 8
  batch_max_length: 101 # Percentile 99 of the dataset. 
  imgH: 64
  rgb: false
  sensitive: True
  data_filtering_off: False
  character: "¡!¿?&()-:;.,0123456789ABCDEFGHIJLMNOPQRSTUVXYZabcdefghijlmnopqrstuvxyzÑñç "
